// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/wupt/work/mucsgo/src/models/socket';
import model_2 from '/Users/wupt/work/mucsgo/src/models/sys';
import model_3 from '/Users/wupt/work/mucsgo/src/models/user';
import model_4 from '/Users/wupt/work/mucsgo/src/.umi-production/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'socket', model: model_1 },
model_2: { namespace: 'sys', model: model_2 },
model_3: { namespace: 'user', model: model_3 },
model_4: { namespace: '@@initialState', model: model_4 },
} as const
